### ISSUE TITLE
Login 500 error

### ISSUE THREAD

**Issue by SJS-dev** [gpodder/mygpo#719] opened 2022-05-09 10:06 UTC
can't register

**Comment by tricon** [comment] 2022-05-20 04:36
This is a long-shot, but if I could get access to the server or logs, I would be happy to trace this issue down and resolve it. 

This issue has been outstanding for seven months. I don't mean to imply anything negative regarding the maintainers and operators; I appreciate everyone's work on the project. I also feel that FLOSS projects, in order to attract users of all types and to continue to demonstrate their superiority, need to embrace reliability and rapid resolution. 

Of course, these depend upon availability and resources; but if such are unable to be dedicated to resolving this languishing issue, perhaps a path needs to be identified such that additional maintainers and operators can be brought in. 

Please understand that I state the above with the most sincere tone and intentions.

**Comment by Eboreg** [comment] 2022-05-23 11:18
@tricon I suggested a possible solution here: https://github.com/gpodder/mygpo/issues/647#issuecomment-1112098223

**Comment by gabe31415** [comment] 2022-05-27 18:07
I can't register :(

**Comment by thawn** [comment] 2022-06-10 06:40
This is a duplicate of #647

**Comment by fundatillus** [comment] 2022-07-01 16:21
Duplicate of #647

**Closed by fundatillus** 2022-07-01 16:21 UTC
