### ISSUE TITLE
registration error 500

### ISSUE THREAD

**Issue by Tealk** [gpodder/mygpo#681] opened 2021-12-25 18:30 UTC
Hello,

when I try to register(mail) on gpodder.net I get the following error message:
![grafik](https://user-images.githubusercontent.com/12276250/147391390-0a5e15b7-faa2-4be6-a8d9-15e6a3d61549.png)

Sorry if this doesn't belong here but I haven't found an email or other contact anywhere on the website.

**Comment by jose-oc** [comment] 2021-12-29 17:29
Same issue trying to log in with Google for first time.

**Comment by msdosfx** [comment] 2021-12-30 12:19
Same here. I believe they are aware. Seems to have been a problem since at least October, maybe longer.

**Comment by lkreimann** [comment] 2022-01-03 10:06
Had this too a few minutes ago

**Comment by Ryochan7** [comment] 2022-01-06 15:10
Can't find my old post about it but this problem has to be a server issue. Been testing running mygpo on Linode with production settings and the SMTP email backend running. I can register and activate accounts from email links without any issue. The view code works.

Would anyone be interested in a hard fork of this project? Tried to help here but that went nowhere after several months. I could probably run a public instance for a bit.

**Comment by Ryochan7** [comment] 2022-01-11 03:21
Going to bite the bullet and make an instance public. Had some problems getting an email server configured. As of now, any registration email sent out is going to end up listed as Spam. I cannot guarantee that this instance will be online for long; I am only considering shooting for March 2022 right now. Going to have to remove some gPodder branding as the code gets changed.

https://alphagpo.ryochan7.org/

Repos:
https://github.com/Ryochan7/alphagpo
https://github.com/Ryochan7/alphagpo-feedserver

**Comment by lucasnz** [comment] 2022-01-11 09:10
@Ryochan7 - thanks. I've been trying to get mygpo to run in docker so I can have my own instance - but haven't succeeded yet. I have some testing to do with sync between my Garmin watch and Android phone, so may take advantage of your server while it's there. If you want some tips on how to do the email, I may be able to assist. What platform are you running your server on (Debian/Ubuntu, docker or something else)?? I may try and set one up myself, so any tips would be appreciated.

**Comment by Ryochan7** [comment] 2022-01-11 16:07
I am running Debian 10 on a Linode VPS. Running the server software in the native environment so Docker is not being used. Had to solve a few issues to get the feedservice software to work properly again so my instance does not need to rely on the gPodder service.

Got a gPodder client linked to the instance and a few podcast feeds are now on the service. Need to look into how the info for the Directory section is supposed to be generated. Still a lot to play with.

**Comment by Ryochan7** [comment] 2022-01-11 18:14
Noticed that Spamhaus and Gmail have been blocking registration emails. Trying to get the server IP whitelisted so emails do not get bounced.

**Comment by deisi** [comment] 2022-01-29 15:48
Have a place to send some money? I tried running my own instance on my home server but it produced the same error. Then I found your "fork" and could register. Now lets see if I can run this my self as well.

**Comment by clach04** [comment] 2022-03-26 21:27
@Tealk just saw this issue first (after seeing the same error), please could you update the original description to link to #647? It would save having to read the entire thread before seeing the link to the first report. Thanks!

**Comment by allentown521** [comment] 2022-05-07 01:43
Push, please fix

**Comment by fundatillus** [comment] 2022-07-01 16:22
Duplicate of #647

**Closed by fundatillus** 2022-07-01 16:22 UTC
