### ISSUE TITLE
Cannot subscribe to any podcast using web interface

### ISSUE THREAD

**Issue by jnuss** [gpodder/mygpo#608] opened 2021-06-24 14:15 UTC
When clicking on the subscribe button for a podcast, nothing happens.

**Comment by barryvdh** [comment] 2021-07-25 09:46
Same thing happens to me. Not sure how to subscribe?

**Comment by Waynosan** [comment] 2021-08-12 00:43
Same here... tried different browsers.  Have no idea how to get this to work.  Maybe this is project is abandoned?  Don't know, just trying to use with the Garmin podcasts app.

**Comment by Ryochan7** [comment] 2021-10-01 16:24
Maybe the celery worker is not running on the server?

**Comment by plum** [comment] 2022-02-10 13:24
Same here on gpodder.net, as of Feb. 2022

**Comment by fundatillus** [comment] 2022-07-06 12:23
Duplicate of #520.

**Closed by fundatillus** 2022-07-06 12:23 UTC
