### ISSUE TITLE
No Register possible

### ISSUE THREAD

**Issue by pediehl** [gpodder/mygpo#711] opened 2022-04-16 10:16 UTC
I get allways 500 no new user are posible

![image](https://user-images.githubusercontent.com/934151/163671128-2704457d-d51a-44a1-83d1-0e80cf6223c8.png)

**Comment by jlariviere1** [comment] 2022-04-18 20:49
Same.  I've been trying for months to register and always get the 500 error.  Desktop, Mobile, different browsers, different passwords

**Comment by jelmer** [comment] 2022-04-23 12:29
Anything in your logs? When first setting up mygpo, I found that the inability to send email caused this error.

**Comment by veganhead** [comment] 2022-04-25 18:01
Same here with trying to set up a gpodder account. 
Tried registering on 3 different devices, linux, Windows 10 and Android, using 3 different browsers, using wifi and 4g. 
Same issue each time "Error 500 - internal server error"

**Comment by Eboreg** [comment] 2022-05-01 16:17
The error message is a bit misleading, since HTTP 500 (at least in Django) basically just means that some piece of code raised an exception that wasn't handled. Anyway, here is an older issue for the same problem, where I made a guess about the cause and suggested a solution: #647

**Comment by oddtoddy** [comment] 2022-05-05 10:02
Same issue.

**Comment by allentown521** [comment] 2022-05-07 01:42
Push, please fix

**Comment by CaptainKoons** [comment] 2022-05-29 05:15
Same issue.

**Comment by fundatillus** [comment] 2022-07-01 16:21
Duplicate of #647

**Closed by fundatillus** 2022-07-01 16:21 UTC
