### ISSUE TITLE
Podcast Lists > Add Podcast not finding podcasts

### ISSUE THREAD

**Issue by orschiro** [gpodder/mygpo#101] opened 2018-04-26 11:03 UTC
Attaching some screenshots. I am doing something incorrectly?

Thanks!

![image](https://user-images.githubusercontent.com/170947/39302234-38e36602-4952-11e8-8506-c61c831b4735.png)

![image](https://user-images.githubusercontent.com/170947/39302245-3f517e0c-4952-11e8-98f8-432b30f98280.png)

**Comment by stephenjudge** [comment] 2018-09-08 22:52
Confirmed, you can't add a podcast to a list either by adding the feed directly or searching by the feed title, even if the feed is already in the gpodder.net directory. This is definitely a bug. It's a shame because this is exactly the feature I need right now to share a feed list with a friend.

**Comment by Ban3** [comment] 2019-10-11 11:11
It's due to misconfigured server. Looking at the browsers console reveals this:

> Load denied by X-Frame-Options: https://gpodder.net/user/XXXX/list/XXXX/search?q=XXXX does not permit framing.

Testing with Firefox extension "Ignore X-Frame-Options Header" adding to lists works fine.

**Comment by stefankoegl** [comment] 2019-10-18 20:42
@Ban3 thanks for the pointing that out. It should be fixed now. Can you verify?

**Comment by Ban3** [comment] 2019-10-19 11:37
@stefankoegl Verified working. :thumbsup:

**Closed** 2019-10-19 11:44 UTC
